name: ctf2
on:
  pull_request_target:
  push:
    branches: [main]
jobs:
  ctf2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request_target'
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - uses: actions/checkout@v2
        if: github.event_name != 'pull_request_target'
      - name: run tests
        run: make test
      - uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Mona the Octocat'
          test: test
